### Get data from places with text query
POST https://places.googleapis.com/v1/places:searchText
Content-Type: application/json
X-Goog-Api-Key: {{api_key}}
X-Goog-FieldMask: places.id,places.displayName,places.formattedAddress

{
  "textQuery": "Bromo"
}

### Place details (photo reference)
GET https://maps.googleapis.com/maps/api/place/details/json?
    place_id=ChIJQUp5q6o31i0R3aXS7DYNpK0&
    fields=photos&
    key={{api_key}}
Content-Type: application/json

### Get photo
GET https://maps.googleapis.com/maps/api/place/photo?
    maxwidth=1600&
    photo_reference=AcJnMuG0U_kZaSALbkEn0d8fhnngetBtTiblRKAlJ8DsOqsGNRvQmMG-E95vihWnmz0740mLfzA_fxbnPtmb1XCKHeVO5jFrYV8HwmCnQXgQ3Vb3bchLv2hpD_DFmSqEt4bHjS2-N9UzLvbTecTIOCPbh4clifBe5IzKOSOEB8QwJGlY8ULO
    &key={{api_key}}

### Get data from places
GET https://maps.googleapis.com/maps/api/place/findplacefromtext/json?
    input=Bromo&
    inputtype=textquery&
    fields=formatted_address%2Cname%2Crating%2Copening_hours%2Cgeometry&
    language=en&
    key={{api_key}}

### Get places of interest
GET https://maps.googleapis.com/maps/api/place/nearbysearch/json?
    location=-7.967498%2C112.633308&
    radius=200000&
    type=point_of_interest&
    language=en&
    key={{api_key}}
